export default class ActionType {
    static ISLOGGEDIN = "ISLOGGEDIN";

    static LOGIN = "LOGIN";
    static LOGIN_SUCCESS = "LOGIN_SUCCESS";
    static LOGIN_FAIL = "LOGIN_FAIL";

    static FORGOT_PASSWORD = "FORGOT_PASSWORD";
    static FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
    static FORGOT_PASSWORD_FAIL = "FORGOT_PASSWORD_FAIL";

    static UPDATE_PASSWORD = "UPDATE_PASSWORD";
    static UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";
    static UPDATE_PASSWORD_FAIL = "UPDATE_PASSWORD_FAIL";

    static LOGOUT = "LOGIN_OUT";
    static LOGOUT_SUCCESS = "LOGIN_OUT_SUCCESS";

    static SIGNUP = "SIGNUP";
    static SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
    static SIGNUP_FAIL = "SIGNUP_FAIL";

    /**
    |--------------------------------------------------
    | ORDER Actions
    |--------------------------------------------------
    */

    static GET_CUSTOMERS = "GET_CUSTOMERS";
    static GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
    static GET_CUSTOMERS_FAIL = "GET_CUSTOMERS_FAIL";

    static GET_FLAVOURS_PACKS = "GET_FLAVOURS_PACKS";
    static GET_FLAVOURS_PACKS_SUCCESS = "GET_FLAVOURS_PACKS_SUCCESS";
    static GET_FLAVOURS_PACKS_FAIL = "GET_FLAVOURS_PACKS_FAIL";

    static GET_QUANTITY_SCHEME = "GET_QUANTITY_SCHEME";
    static GET_QUANTITY_SCHEME_SUCCESS = "GET_QUANTITY_SCHEME_SUCCESS";
    static GET_QUANTITY_SCHEME_FAIL = "GET_QUANTITY_SCHEME_FAIL";
    
    static GET_FREIGHT_CALCULATION = "GET_FREIGHT_CALCULATION";
    static GET_FREIGHT_CALCULATION_SUCCESS = "GET_FREIGHT_CALCULATION_SUCCESS";
    static GET_FREIGHT_CALCULATION_FAIL = "GET_FREIGHT_CALCULATION_FAIL";
    
    static ADD_ORDER = "ADD_ORDER";
    static ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
    static ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
    
    static PLACE_CONFIRM_ORDER = "PLACE_CONFIRM_ORDER";
    static PLACE_CONFIRM_ORDER_SUCCESS = "PLACE_CONFIRM_ORDER_SUCCESS";
    static PLACE_CONFIRM_ORDER_FAIL = "PLACE_CONFIRM_ORDER_FAIL";
    
    static REMOVE_PRODUCT = "REMOVE_PRODUCT";
    static REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
    static REMOVE_PRODUCT_FAIL = "REMOVE_PRODUCT_FAIL";

    // LOCAL DATA.
    static SAVE_PLACED_ORDER_SUCCESS = "SAVE_PLACED_ORDER_SUCCESS";
    
    static RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST";
    
    /**
    |--------------------------------------------------
    | REPORT Actions
    |--------------------------------------------------
    */

    static GET_REPORT = "GET_REPORT";
    static GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
    static GET_REPORT_FAIL = "GET_REPORT_FAIL";

    static GET_REPORT_ORDER_LIST = "GET_REPORT_ORDER_LIST";
    static GET_REPORT_ORDER_LIST_SUCCESS = "GET_REPORT_ORDER_LIST_SUCCESS";
    static GET_REPORT_ORDER_LIST_FAIL = "GET_REPORT_ORDER_LIST_FAIL";

    static GET_REPORT_DETAILS = "GET_REPORT_DETAILS";
    static GET_REPORT_DETAILS_SUCCESS = "GET_REPORT_DETAILS_SUCCESS";
    static GET_REPORT_DETAILS_FAIL = "GET_REPORT_DETAILS_FAIL";

    static EDIT_REPORT = "EDIT_REPORT";
    static EDIT_REPORT_SUCCESS = "EDIT_REPORT_SUCCESS";
    static EDIT_REPORT_SUCCESS_ORDER = "EDIT_REPORT_SUCCESS_ORDER";
    static EDIT_REPORT_FAIL = "EDIT_REPORT_FAIL";

    /**
    |--------------------------------------------------
    | DEPOSIT Actions
    |--------------------------------------------------
    */

   static SUBMIT_DEPOSIT_FORM = "SUBMIT_DEPOSIT_FORM";
   static SUBMIT_DEPOSIT_FORM_SUCCESS = "SUBMIT_DEPOSIT_FORM_SUCCESS";
   static SUBMIT_DEPOSIT_FORM_FAIL = "SUBMIT_DEPOSIT_FORM_FAIL";


}
